authors = ["d1y <chenhonzhou@gmail.com>"]
description = "Allow to use common word completion and snippets for Helix editor"
id = "scls"
name = "Simple completion"
repository = "https://github.com/d1y/simple-completion-zed"
schema_version = 1
version = "0.0.1"

[language_servers.scls]
name = "Simple completion LSP"

# TODO: add full language support?
# I just added some of the languages ​​I know how to use
languages = [
  "TypeScript",
  "JavaScript",
  "Vue.js",
  "Go",
  "Go Mod",
  "Go Work",
  "Shell Script",
  "HTML",
  "Scheme",
  "Lua",
  "Dart",
  "Zig",
  "C",
  "C++",
  "CSS",
  "JSON",
  "Markdown",
  "Ruby",
  "Rust",
  "YAML",
  "TOML",

  "Git Commit",
  "Git Ignore"
]

# At least I don't understand yet, what are `language_ids`?
[language_ids]
Dart = "dart"
Go = "go"
"Go Mod" = "gomod"
"Go Work" = "gowork"
HTML = "html"
JavaScript = "javascript"
Lua = "lua"
Scheme = "scm"
"Shell Script" = "shell"
TypeScript = "typescript"
"Vue.js" = "vuejs"
Zig = "zig"
C = "c"
"C++" = "cpp"
CSS = "css"
JSON = "json"
Markdown = "markdown"
Python = "python"
Ruby = "ruby"
Rust = "rust"
YAML = "yaml"
TOML = "toml"
"Git Commit" = "git_commit"
"Git Ignore" = "git_ignore"